<?php

/** @var $this SlideTwo */

use ProtectedNet\FrontendTest\Partials\HeroContent\SlideTwo\SlideTwo;

?>

<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('slider-2.jpg') ?>');"></div>


<div class="<?= $this->getElementName('content') ?>">
  <div class="grid-container">
    <div class="grid-x">
      <div class="cell">
        <h1 class="<?= $this->getElementName('title') ?>">Staffing <strong>solutions</strong> for you</h1>
      </div>
    </div>
  </div>
  <div class="<?= $this->getElementName('btnContainer grid-x') ?>">
    <div class="<?= $this->getElementName('column large-6 medium-6 small-12') ?>">
  <a class="<?= $this->getElementName('button') ?>"href="" style="float:right;"><p>Search a Job &nbsp;</p><p class="icon"><i class="arrow right"></i></p></a>
</div>
    <div  class="<?= $this->getElementName('column large-6 medium-6 small-12') ?>">
    <a class="<?= $this->getElementName('button') ?>"href="" style="float:left;"><p>Post a Resume &nbsp;</p><p class="icon"><i class="arrow right"></i></p></a></div>
  </div>
</div>