<?php
/** @var $this TextSideImage */

use ProtectedNet\FrontendTest\Partials\HeroContent\PricingSlide\PricingSlide;
?>

<div class="<?= $this->getElementName('content') ?>">
    <div class="<?= $this->getElementName('titleBlock') ?>">
        <h2 class="<?= $this->getElementName('title') ?>"><b>Plans &</b> pricing</h2>
        <p class="<?= $this->getElementName('subTitle') ?>">LOREM IPSUM</p>
    </div>
    <div class="<?= $this->getElementName('optionsBlock') ?>">
        <div class="<?= $this->getElementName('option') ?>">
            <div class="<?= $this->getElementName('optionTop') ?>">
                <h3 class="<?= $this->getElementName('optionType') ?>">
                    Start Up
                </h3>
                <h2 class="<?= $this->getElementName('optionPrice') ?>">
                    $29
                </h2>
                <p class="<?= $this->getElementName('optionDesc') ?>">
                    1 job for 30 days
                </p>
            </div>
            <div class="<?= $this->getElementName('optionBottom') ?>">
                <p class="<?= $this->getElementName('optionBotText') ?>">One Time Fee<br>Allows 5 Job Postings<br>Highlighted Job Post<br>Posted For 90 Days</p>
                <a class="<?= $this->getElementName('optionLink') ?>" href="">Shop now! | ></a>
            </div>
        </div>
        <div class="<?= $this->getElementName('option') ?>">
            <div class="<?= $this->getElementName('optionTop') ?>">
                <h3 class="<?= $this->getElementName('optionType') ?>">
                    Enterprise
                </h3>
                <h2 class="<?= $this->getElementName('optionPrice') ?>">
                    $69
                </h2>
                <p class="<?= $this->getElementName('optionDesc') ?>">
                    1 job for 30 days
                </p>
            </div>
            <div class="<?= $this->getElementName('optionBottom') ?>">
            <p class="<?= $this->getElementName('optionBotText') ?>">One Time Fee<br>Allows 5 Job Postings<br>Highlighted Job Post<br>Posted For 90 Days</p>
                <a class="<?= $this->getElementName('optionLink') ?>" href="">Shop now! | ></a>
            </div>
        </div>
        <div class="<?= $this->getElementName('option') ?>">
            <div class="<?= $this->getElementName('optionTop') ?>">
                <h3 class="<?= $this->getElementName('optionType') ?>">
                    Company
                </h3>
                <h2 class="<?= $this->getElementName('optionPrice') ?>">
                    $329
                </h2>
                <p class="<?= $this->getElementName('optionDesc') ?>">
                    1 job for 30 days
                </p>
            </div>
            <div class="<?= $this->getElementName('optionBottom') ?>">
            <p class="<?= $this->getElementName('optionBotText') ?>">One Time Fee<br>Allows 5 Job Postings<br>Highlighted Job Post<br>Posted For 90 Days</p>
                <a class="<?= $this->getElementName('optionLink') ?>" href="">Shop now! | ></a>
            
            </div>
        </div>
    </div>
</div>
