<?php
/** @var $this TextSideImage */

use ProtectedNet\FrontendTest\Partials\HeroContent\TextSideImage\TextSideImage;
?>
<div>
  <div class="<?= $this->getElementName('content') ?>">
    <h2 class="<?= $this->getElementName('title') ?>"><?= $this->getData("title") ?></h2>
    <div class="<?= $this->getElementName('itemContainer') ?>">
    <?php $count = 1; ?>
      <?php foreach($this->getSubElements() as $key => $subElement): ?>
        <?php $count = ($count + 1) % 2; ?>

          <div class="<?= $this->getElementName('subItem') ?>">
          <div class="<?= $this->getElementName('subImageContainer').$count ?>">
          <img class="<?= $this->getElementName('subImage') ?>" src=<?= $this->getImg($subElement["subImage"]); ?>></img>
          </div>
        <h3 class="<?= $this->getElementName('subTitle').$count ?>"><?= $subElement["subTitle"] ?></h3>
        <p class="<?= $this->getElementName('subText').$count ?>"><?= $subElement["subText"] ?></p>

      </div>


        <?php endforeach; ?>
    </div>
  </div>
</div>