<?php

/** @var $this StatsSlide */

use ProtectedNet\FrontendTest\Partials\HeroContent\StatsSlide\StatsSlide;
use ProtectedNet\FrontendTest\Components\Statistic\Statistic;
use Packaged\Dispatch\ResourceManager;
?>

<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('plant.jpg') ?>');">


  <div class="<?= $this->getElementName('content') ?>">
    <h2 class="<?= $this->getElementName('title') ?>">Site <b>stats</b></h2>
    <div class="<?= $this->getElementName('columnContainer') ?>">
<?= 
Statistic::i()
  ->setTitle("Excepteur sint occaecat")
  ->setText("Excepteur sint occaecat")
  ->setPercent("75");
  ?><?=
  Statistic::i()
  ->setTitle("Excepteur sint occaecat")
  ->setText("Excepteur sint occaecat")
  ->setPercent("25")
  ->rightSide();
  ?><?=
  Statistic::i()
  ->setTitle("Excepteur sint occaecat")
  ->setText("Excepteur sint occaecat")
  ->setPercent("50");
  ?><?=
  Statistic::i()
  ->setTitle("Excepteur sint occaecat")
  ->setText("Excepteur sint occaecat")
  ->setPercent("75")
  ->rightSide();
?>
    </div>
  </div>