<?php
/** @var $this StatsSlide */

use ProtectedNet\FrontendTest\Partials\HeroContent\StatsSlide\StatsSlide;
?>

<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('plant.jpg') ?>');">


<div class="<?= $this->getElementName('content') ?>">
<h2 class="<?= $this->getElementName('title') ?>">Site <b>stats</b></h2>
    <div class="<?= $this->getElementName('columnContainer') ?>">
        
    <div class="<?= $this->getElementName('subItem') ?>">
          <div class="<?= $this->getElementName('subStatContainer0')?>">
            <div class="<?= $this->getElementName('subCircleContainer')?>">
            <svg class="<?= $this->getElementName('subSvg1')?>" width="120" height="120" viewBox="0 0 120 120">
            <circle cx="60" cy="60" r="54" fill="none" stroke="white" stroke-width="12" />
            <circle cx="60" cy="60" r="54" fill="none" stroke="#23ba85" stroke-width="12"
                stroke-dasharray="339.292" stroke-dashoffset="84.823" transform/> 
                </svg>
                <p class="<?= $this->getElementName('circleText')?>">75%</p>
            </div>
          </div>
          <div class="<?= $this->getElementName('subTextContainer0') ?>">
        <h3 class="<?= $this->getElementName('subTitle0') ?>">Lorem Ipsum</h3>
        <p class="<?= $this->getElementName('subText0') ?>">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
</div>

    </div>
    <div class="<?= $this->getElementName('subItem') ?>">
          <div class="<?= $this->getElementName('subStatContainer1')?>">
            <div class="<?= $this->getElementName('subCircleContainer')?>">
            <svg class="<?= $this->getElementName('subSvg1')?>" width="120" height="120" viewBox="0 0 120 120">
            <circle cx="60" cy="60" r="54" fill="none" stroke="white" stroke-width="12" />
            <circle cx="60" cy="60" r="54" fill="none" stroke="#23ba85" stroke-width="12"
                stroke-dasharray="339.292" stroke-dashoffset="84.823" transform/> 
                </svg>
                <p class="<?= $this->getElementName('circleText')?>">75%</p>
            </div>
          </div>
          <div class="<?= $this->getElementName('subTextContainer1') ?>">
        <h3 class="<?= $this->getElementName('subTitle1') ?>">Lorem Ipsum</h3>
        <p class="<?= $this->getElementName('subText1') ?>">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
</div>
</div>

</div>