<?php

/** @var $this Home */

use ProtectedNet\FrontendTest\Pages\Home\Home;

?>
<head>
<link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">

</head>
<div>
<?= $this->_getAboutUs(); ?>

<?= $this->_getTextOnImage(); ?>

<?= $this->_getPricingSlide(); ?>

<?= $this->_getStatsSlide(); ?>
</div>