<?php
/** @var $this SlideThree */

use ProtectedNet\FrontendTest\Partials\HeroContent\SlideThree\SlideThree;

?>


<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('slider-3.jpg') ?>');">

<div class="<?= $this->getElementName('content') ?>">
  <div class="grid-container">
    <div class="grid-x">
      <div class="cell">
        <h1 class="<?= $this->getElementName('title') ?>">The <strong>perfect</strong> job, just one click away</h1>
      </div>
    </div>
  </div>
  <div class="<?= $this->getElementName('btnContainer grid-x') ?>">
    <div class="<?= $this->getElementName('column large-6 medium-6 small-12') ?>">
  <a class="<?= $this->getElementName('button') ?>"href="" style="float:right; transform:translate(50%, 0%);"><p>Succeed Now &nbsp;</p><p class="icon"><i class="arrow right"></i></p></a>
</div>

  </div>
</div>

</div>
