<?php
/** @var $this TextSidelineImage */

use ProtectedNet\FrontendTest\Partials\WorkingContent\TextSidelineImage\TextSidelineImage;
?>


<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('slider-1.jpg') ?>');"></div>


<div class="<?= $this->getElementName('content') ?>">
  <div class="grid-container">
    <div class="grid-x">
      <div class="cell medium-6">
        <h1 class="<?= $this->getElementName('title') ?>"><?= $this->getData("b") ?>Lorem ipsum dolor sit amet, consectetur.</h1>
        <p class="<?= $this->getElementName('text') ?>">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ipsa repellendus repudiandae?</p>
        <ul class="<?= $this->getElementName('list') ?>">
          <li class="<?= $this->getElementName('list', 'item') ?>">Lorem ipsum dolor.</li>
          <li class="<?= $this->getElementName('list', 'item') ?>">Lorem ipsum dolor sit.</li>
        </ul>
      </div>
    </div>
  </div>
</div>